import { Inter } from "next/font/google";
import "./globals.css";
import {Analytics} from '@vercel/analytics/next';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Piyush portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6592968913601720"
     crossorigin="anonymous"></script>
      </head>
      <body className={inter.className}>{children}<Analytics /></body>
    </html>
  );
}
